services:
  backend:
    build:
      context: .
      target: development-image
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/src/
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    image: "postgres:15.7-alpine3.20"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: um_db

    healthcheck:
      test: "exit 0"

  redis:
    image: "redis:7.0.5-alpine"
    ports:
      - "6379:6379"

volumes:
  data: